# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='Anonymous', max_length=45),
        ),
    ]
