# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='auth', to='book_reviewer.Book'),
        ),
    ]
