# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='anonymous', max_length=45),
            preserve_default=False,
        ),
    ]
