# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_in_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='in_print',
            field=models.BooleanField(default=True),
        ),
    ]
